name: Add Contributor to List

on:
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add contributor
        run: |
          echo "- [@${{ github.actor }}](https://github.com/${{ github.actor }})" >> CONTRIBUTORS.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CONTRIBUTORS.md
          git commit -m "Added @${{ github.actor }} as a contributor 🎉"
          git push origin main
